"""
Build a single TheAgent0.exe that launches the proxy + Web UI.

Usage (from the repo root, inside the venv):
    python build_exe.py

Requirements:
    pip install pyinstaller

The resulting exe lives in dist/TheAgent0.exe. It still needs Ollama
running locally (Ollama is a separate ~4GB binary; bundling it would be
wrong). Double-clicking the exe starts the proxy and opens the browser.

Bundled inside the exe:
    - core/*.py, config.py, data/*.py
    - TheAgent0UI/          (web UI)
    - docs/                 (RAG docs — optional, can be large)

NEVER bundled — the exe reads/writes them from alongside itself at runtime:
    - cad_db/               (vector store — writable)
    - runtime_overrides.json (user-edited, contains ENCRYPTED api_key)
    - .secret_key           (Fernet key on non-Windows)
    - proxy.log / gateway.log

The DATAS tuple below is the source of truth for what ships. If you add new
bundled assets, make sure they NEVER contain secrets — this exe may be
shared. runtime_overrides.json and .secret_key are deliberately omitted.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
NAME = "TheAgent0"
ENTRY = ROOT / "launcher.py"

# Hidden-imports PyInstaller may miss (dynamic imports in langchain, chromadb)
HIDDEN = [
    "chromadb", "chromadb.config", "chromadb.api", "chromadb.telemetry",
    "langchain_core", "langchain_text_splitters", "langchain_community",
    "tiktoken_ext", "tiktoken_ext.openai_public",
    "pypdf", "docx2txt", "unstructured",
    "win32crypt", "win32cred",
    "core.agent", "core.orchestrator", "core.tools", "core.tool_schema",
    "core.context", "core.providers", "core.permissions", "core.query",
    "core.secrets", "core.browser", "core.discord_gateway", "core.scheduler",
]

DATAS = [
    ("TheAgent0UI", "TheAgent0UI"),
    ("core", "core"),
    ("data", "data"),
    ("docs", "docs"),
    ("config.py", "."),
]


def _data_args() -> list[str]:
    sep = ";" if sys.platform.startswith("win") else ":"
    out = []
    for src, dst in DATAS:
        p = ROOT / src
        if not p.exists():
            print(f"[build] skipping missing data: {src}")
            continue
        out += ["--add-data", f"{p}{sep}{dst}"]
    return out


def _hidden_args() -> list[str]:
    out = []
    for m in HIDDEN:
        out += ["--hidden-import", m]
    return out


def _write_launcher() -> None:
    """Tiny entry point that sets cwd to the exe folder, then starts proxy.main()."""
    ENTRY.write_text(
        """# Auto-generated by build_exe.py — do NOT edit manually.
import multiprocessing, os, sys, webbrowser, threading, time
from pathlib import Path

def _main():
    multiprocessing.freeze_support()
    if getattr(sys, 'frozen', False):
        base = Path(sys._MEIPASS)  # PyInstaller temp unpack dir
        work = Path(sys.executable).parent  # folder next to the exe
        os.chdir(str(work))
        sys.path.insert(0, str(base))
    from config import PROXY_PORT
    from core.proxy import main as proxy_main

    def _open_browser():
        time.sleep(2)
        try:
            webbrowser.open(f'http://localhost:{PROXY_PORT}')
        except Exception:
            pass
    threading.Thread(target=_open_browser, daemon=True).start()
    proxy_main()

if __name__ == '__main__':
    _main()
""",
        encoding="utf-8",
    )


def main() -> int:
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("[build] PyInstaller missing. Install with: pip install pyinstaller")
        return 1

    _write_launcher()

    # Clean old build artifacts
    for d in ("build", "dist"):
        p = ROOT / d
        if p.exists():
            shutil.rmtree(p)
    spec = ROOT / f"{NAME}.spec"
    if spec.exists():
        spec.unlink()

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onefile",
        "--name", NAME,
        "--noconfirm",
        "--clean",
        # Console mode so users see startup logs; use --noconsole for silent.
        "--console",
        *_data_args(),
        *_hidden_args(),
        str(ENTRY),
    ]
    print("[build] running:", " ".join(cmd))
    res = subprocess.run(cmd, cwd=str(ROOT))
    if res.returncode != 0:
        print(f"[build] FAILED (exit {res.returncode})")
        return res.returncode

    exe = ROOT / "dist" / (f"{NAME}.exe" if sys.platform.startswith("win") else NAME)
    print(f"[build] OK → {exe}")
    print("[build] Reminder: Ollama must still be running locally.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
